var quotes = [
	'"You never lose by loving. You always lose by holding back." - Barbara de Angelis',
	'You try to fix my toes.',
	'That time we made friends from Argentina while hiking the Inca Trail.',
	'"Love is being stupid together." - Paul Valery',
	'You thought that rosemary would be good in pasta.',
	'"You know you\'re in love when you can\'t fall asleep because reality is finally better than your dreams." - Dr. Seuss',
	'"And ever has it been known that love knows not its own depth until the hours of seperation." - Khalil Gibran',
	'"Everything in me feels fluttering and free, like I could take off from the ground at any second. Music, I think, he. m akes m e feel like music." - Lauren Oliver',
	'You\'re passionate enough to climb mountains even when you\'re body hates you for it.',
	'"In the arithmetic of love, one plus one equals everything, and two minus one equals nothing." - Mignon McLaughlin',
	'That time you walked me out of the RJD2 show and seduced me, despite your own admission of guilt.',
	'That time I made you watch Cabin in the Woods and you freaked out.',
	'"What lies behind us, and what lies before us are tiny matters compared to what lies within us." - Ralph Waldo Emerson',
	'You\'ve showed me the value of entertainment through trashy TV.',
	'Back rubs.',
	'"When I give I give myself." - Walt Whitman',
	'"When someone loves you, the way they talk about you is different. You feel safe and comfortable." - Jess C. Scott',
	'"At the touch of love, everyone becomes a poet." - Plato',
	'All the times you called me out for slipping into my lucky charms accent.',
	'"The music in his laughter has a way of rounding off the missing notes in her soul." - Gloria Naylor',
	'"To get the full value of joy you must have someone to divide it with." - Mark Twain',
	'"He\'s more myself than I am. Whatever our souls are made of, his and mine are the same." - Emily Bronte',
	'"On no.  Don\'t smile. You\'ll kill me. I stop breathing when you smile." - Tessa Dare',
	'"The most precious possession that ever comes to a man in this world is a womans heart." - Josiah G. Holland',
	'You wear sparkley things.',
	'That time we decorated the christmas tree and listened to "A Charlie Brown Christmas"',
	'That time I threatened to out us at work by slapping you in the butt and you replied encouraging me to do so.',
	'You\'re a little forgetful, too. (But not really...)',
	'I\'m your hun.',
	'That one time Carla said something inappropriate about us in front of everyone. (Get it? One time?)',
	'"To love and be loved is to feel the sun from both sides." - David Viscott',
	'You talk funny when you eat the ume candy.',
	'That time I took you to a haunted restaurant and didn\'t tell you but you figured it out on your own.',
	'That time we were driving across the Golden Gate Bridge and the sun was setting in just the right way.',
	'You have a sweet shart t-shirt',
	'That face you make in the churros picture.',
	'"I love how she makes me feel. Like anything is possible. Or like life is worth living." - Tom Hansen',
	'"For suddenly, I saw you there...And through foggy London town...The sun was shining everywhere..." - George Gershwin',
	'You like capers and they\'re sort of like pickles.',
	'You slightly turn your head every time you\'re confused.',
	'"They say a person needs just three things to be truly happy in this world: someone to love, something to do, and something to hope for." - Tom Bodett',
	'"The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart." - Helen Keller',
	'"One love, one heart, one destiny." - Bob Marley',
	'"To love a person is to learn the song...That is in their heart...And to sing it to them...When they have forgotten." - Anonymous',
	'That time we met the Alpacas on the Inca Trail.',
	'"The very essence of romance is uncertainty." - Oscar Wilde',
	'"The most important thing in life is to learn how to give out love, and to let it come in." - Morrie Schwartz',
	'"He stepped down, trying not to look long at her, as if she were the sun, yet he saw her, like the sun, even without looking." - Leo Tolstoy',
	'Your laugh makes me laugh.',
	'Checking the time makes me smile.',
	'That time you had the first shower after hiking for five days and used up all the warm water.',
	'That time we saw a comedy show and you were left drunk on the sidewalk after. (I\'m such a gentleman.)',
	'"We loved with a love that was more than love." - Edgar Allan Poe',
	'That time you asked me where I lived and I said the Upper West Side. You judged me and sent me to talk to Steve Shames.',
	'All the times Steph played that weird birthday song for people at Naked.',
	'The time I showed up late to our first double date and you had already won over my best friends.',
	'All the times we suffered through the C train to see each other.',
	'The moment you fell asleep in our first apartment and I realized you would be there every night from then on.',
	'That time you wrote "I\'m a business man" on a post-it in my office which I left up the entire time I worked there.',
	'Back farts.',
	'"You are, and always have been, my dream." - Nicholas Sparks',
	'"Love does not consist of gazing at each other, but in looking outward together in the same direction." - Antoine de Saint-Exupery',
	'"Love makes your soul crawl out from its hiding place." - Zora Neale Hurston',
	'"Love does not begin and end the way we seem to think it does. Love is a battle, love is a war, love is growing up." - James Baldwin',
	'All the times I see you sitting with my mom and dad and the pride I feel for bringing such a great girl home.',
	'High fives on the 9th.',
	'You won\'t let a tick stop you from living the life you want to live.',
	'That time we ended up at the very top of the Empire State Building and I kind of freaked out.',
	'A bit of a Star Wars nerd, you are.',
	'That time I got you a necklace with a big "R" and was so excited to see you wearing it at work the next day.',
	'That time we saw a Pink Floyd light show, looked into a massive telescope and stood in the weakest hurricane of all time.',
	'That time you came golfing with me and I made you regret it after 10 minutes. (Sorry...I wanted to look good in front of you.)',
	'All the times you show your love by sticking your hand in my face.',
	'"There is always some madness in love. But there is also always some reason in madness." - Friedrich Nietzsche',
	'"When we love, we always strive to become better than we are. When we strive to become better than we are, everything around us becomes better too." - Paulo Coelho',
	'"Once upon a time there was a boy who loved a girl, and her laughter was a question he wanted to spend his whole life answering." - Nicole Krauss',
	'"Those fingers in my hair...That sly come hiter stare...That strips my conscience bare...It\'s witchcraft." - Frank Sinatra',
	'"I feel wonderful because I see...The love light in your eyes." - Eric Clapton',
	'"You don\'t love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear." - Oscar Wilde',
	'"You don\'t love someone because they\'re perfect, you love them in spite of the fact that they\'re not." - Jodi Picoult',
	'"Where there is love there is life." - Mahatma Gandhi',
	'You make hilarious posters for a conservative organization.',
	'You make bowling, my most hated activity, fun.',
	'You called me girl and I wasn\'t allowed to call you girlfriend.',
	'Your confusion in the first few moments when you wakes up makes me smile.',
	'You\'re not afraid to let life lead you unexpected places.',
	'You\'re not offended when I steal the blanket.',
	'That time we were Hall and Oates and that guy across the room freaked out.',
	'That time we went hiking and found the cool ampitheater in the mountain. And then I got us lost.',
	'That time we saw RJD2 and I formally asked you out. And I lost my coat.',
	'That time we worked together to put together the NBC Sports brand positioning.',
	'That time we saw the Giants win the World Series with the rest of SF while running towards yet another Phish show.',
	'That time we relaxed in a pool under a roof of astroturf.',
	'"If she\'s amazing, she won\'t be easy. If she\'s easy, she won\'t be amazing. If she\'s worth it, you won\'t give up. If you give up, you\'re not worthy. Truth is, everybody is going to hurt you. You just gotta find the ones worth suffering for." - Bob Marley',
	'"Now I believe that lovers should be draped in flowers and laid entwined together on a bed of clover and left there to sleep, left there to dream of their happiness." - Conor Oberst',
	'"Romance is the glamour which turns the dust of everyday life into a golden haze." - Carolyn Gold Heilbrun',
	'"One word frees us of all the weight and pain of life: that word is love." - Sophocles',
	'"When love is not madness it is not love." - Pedro Calderon de la Barca',
	'"My wish is that you may be loved to the point of madness." - Andre Breton',
	'"Love is all you need." - The Beatles',
	'"Love is composed of a single soul inhabiting two bodies." - Aristotle',
	'That time you tried to hit golf balls with me. Such a natural.',
	'That time the guy saluted us like a nazi.',
	'You\'re never satisfied with work that doesn\'t make a difference.',
	'I now know who Diane Von Furstenberg is.',
	'Your most feared things in this world are carrots and celery.',
	'A big night for us is delivery and an episode of Homeland.',
	'You are proactively awkward about sexy time.',
	'Instead of locking arms with me you use me as a human shield.',
	'When you try to pout you get a wrinkled up chin and I laugh inside.',
	'That time we saw Rodriguez\'s daughter in concert.',
	'That time I gave you a piggy back ride in front of the Brooklyn Star.',
	'You\'re actually curious about what I\'m saying when I go on a rant about music.',
	'That time we went to a roller skate party in an old church.',
	'Our noses touch just about every time we kiss.',
	'We don\'t need to say anything to understand each other at any moment.',
	'When we hold hands you rub my palm and it makes me melt.',
	'You made doughnuts into people, and then made them into awesome screenprints.',
	'All the times I\'ve taken you to either a concert or a sporting even that you had no interest in, but tried your best to get involved.',
	'That time you picked up and moved across the country with me, not knowing what was waiting for you when you arrived.',
	'That time we created a work-inappropriate turntable session that culminated with Nyanza shutting things down and telling everyone how offended she was.',
	'You loved to turn on the x-ray machine at the most inopportune times.',
	'That time we climbed to the most amazing view in Arizona. And I tore my boxers on the way down.',
	'Romantic comedies make me think about us.',
	'All the times we gave SF shit for not being NYC.',
	'Your eyes are the last thing I see every night.',
	'Just glancing at you still gives me butterflies. (Update: You\'re my wife and this still happens.)',
	'"Being deeply loved by someone gives you strength, while loving someone deeply gives you courage." - Lao Tzu',
	'"Fighting, laughing, loving or crying, if it was with him, I was where I wanted to be." - Jamie McGuire',
	'"Every breath that is in your lungs is a tiny little gift to me." - The White Stripes',
	'"How do you spell \'love\'?" - Piglet    "You don\'t spell it...you feel it." - Pooh',
	'"Because you\'re mine. I walk the line." - Johnny Cash',
	'"Stay with me \'till time turns over." - Phish',
	'"The greatest thing you\'ll ever learn is to love and be loved in return." - Natalie Cole',
	'"I love you. Remember. They cannot take it." - Lauren Oliver',
	'"At last, the skies above are blue. My heart was wrapped up in a clover, the night I looked at you." - Etta James',
	'"For the two of us, home isn\'t a place. It is a person. And we are finally home." - Stephanie Perkins',
	'"What force is more potent than love?" - Igor Stravinsky',
	'"I love you like a fat kid loves cake." - Scott Adams',
	'"We are each of us angels with only one wing, and we can only fly by embracing one another." - Luciano De Crescenzo',
	'"Falling in love is very real, but I used to shake my head when people talked about soul mates, poor deluded individuals grasping at some supernatural ideal not intended for mortals but sounded pretty in a potery book. Then, we met, and everything changed, the cynic has become the converted, the sceptic, an ardent zealot." - E.A. Bucchianeri',
	'"How I wish, how I wish you were here / We\'re just two lost souls swimming in a fish bowl / Year after year..." - Pink Floyd',
	'"People who throw kisses are hopelessly lazy." - Bob Hope',
	'"Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope." - Maya Angelou',
	'"Your voice makes me tremble inside...And your smile is an invitation...For my imagination to go wild." - Anonymous',
	'"With my last breath, I\'ll exhale my love for you. I hope it\'s a cold day, so you can see what you meant to me." - Jerod Kintz',
	'"Sometimes I trip on how happy we could be...And so I put this on my life...Nobody or nothing will ever come between us...And I promise I\'ll give my life." - Jay-Z',
	'"Love is an irresistible desire to be irresistibly desired." - Robert Frost',
	'"I\'d cut up my heart for you to wear if you wanted it." - Margaret Mitchell',
	'"I have loved to the point of madness; that which is called madness, that which to me, is the only sensible way to love." - F. Sagan',
	'"So, I love you because the entire universe conspired to help me find you." - Paulo Coelho',
	'"Do not seek the because - in love there is no because, no reason, no explanation, no solutions." - Anais Nin',
	'"I love you, not only for what you are, but for what I am when I am with you." - Roy Croft',
	'"If I had a flower for every time I thought of you...I could walk through my garden forever" - Alfred Tennyson',
	'"A friend is someone who knows all about you and still loves you." - Elbert Hubbard',
	'"Promise me you\'ll never forget me because if I thought you would, I\'d never leave." - A.A. Milne',
	'"My heart to you is a given: Oh, do give your to me; We\'ll lock them up together, and throw away the key." - Frederick Saunders',
	'"Gravitation is not responsible for people falling in love." - Albert Einstein',
	'You\'re from Hawaii and that\'s definitely an upgrade from Pennsylvania.',
	'You wear short shorts around the apartment.',
	'You always give me the window seat. (Update: also applies to aisle seat.)',
	'When I\'m sick you make me feel better.',
	'You have a glorious glamour shot from your childhood at your house.',
	'You took advantage of my sensitive ears.',
	'You care about the things that I care about.',
	'Randomly licking each other\'s face is an appropriate response during any conversation.',
	'You prefer me to a blanket when you\'re cold.',
	'You don\'t like to look like anyone else.',
	'We bet on things like The Voice.',
	'Dogs are OK now.',
	'You\'re smart enough to figure out your own illness and stubborn enough to force your doctors to test you.',
	'Every once in a while you look like a soccer mom.',
	'Your head fits right by my shoulder when we\'re falling asleep.',
	'Your RAWR face is cute as shit.',
	'You folk my clothing better than I do. (Update: no longer true.)',
	'Your smoothies taste pretty good and you make them for me every once in a while.',
	'You love (to eat) my nose and I love yours. (Update: no update.)',
	'That time we went to the World Series and you kind-of, sort-of rooted for a team aside from the Yankees.',
	'Every time we plotted our covert exit from Naked that, in actuality, was us obviously leaving together.',
	'That time we went to Benihana, which kind of sucked b ut was fun because we were together.',
	'That time you tried to teach me yoga.',
	'That time I stepped in poop with my cool boots, left them outside of our apartment and they magically disappeared.',
	'That time I lost my favorite jacket but it didn\'t matter because I got a date with you.',
	'That time on the balcony when we thought people in another building saw us.',
	'That time we cautiously ate sushi under critical eye in El Cerrito.',
	'That time we dressed up as ghosts and sent a picture to my parents before we were dating.',
	'That time we ate the Alpaca in Cuzco.',
	'That time Leo peed on your desk.',
	'All the times you started a love letter off in such a sweet way and wrapped it up with something totally inappropriate.',
	'The moment we saw a dead possum in the road and you started singing the Phish song.',
	'That time I tried to kiss you and was denied. Twice.',
	'Every time we biked over a bridge between Brooklyn and Manhattan. That view when you can finally see the cityscape.',
	'That time we put a sombraro on the top of our Christmas tree.',
	'That time we bought Sexy Santa at Macy\'s for our Christmas tree. (Update: Sexy Santa got some friends, huh?)',
	'That time you and all the others braved a monsoon at Jones Beach to send me off from Naked.',
	'That time you convinced me I\'d be stupid not to work at Google. Thank you.',
	'That time you, Leo and I snuck off to have a picnic in the village.',
	'That time you bet me the Spurs would win and gave me the kick in the pants I needed to quit smoking.',
	'"Love is like the wind, you can\'t see it but you can feel it." - Nicholas Sparks',
	'"Love lets you find those hidden places in another person, even the ones they didn\'t know were there, even the ones they wouldn\'t have thought to call beautiful themselves." - Wild Awake',
	'"Love is that condition in which the happiness of another person is essential to your own." - Robert A. Heinlein',
	'"Love means never having to say you\'re sorry." - Erich Segal',
	'"Whenever I\'m alone with you you make me feel like I am home again...Whenever I\'m alone with you you make me feel like I am whole again." - The Cure',
	'"They say when you are missing someone that they are probably feeling the same, but I don\'t think it\'s possible for you to miss me as much as I\'m missing you right now." - Edna St. Vincent Millay',
	'"I would fly you to the moon and back if you\'ll be...if you\'ll be my baby." - Savage Garden',
	'"You\'re dangerous," he says. "Why?" "Because you make me believe in the impossible." - Simone Elkeles',
	'"Remember, we\'re madly in love so it\'s all right to kiss me anytime you feel like it." - Peeta',
	'"The very first moment I beheld him, my heart was irrevocably gone." - Jane Austen',
	'"You could hold me and I could hold you. And it would be so peaceful. Completely peaceful. Like the feeling of sleep, but awake in it together." - John Green',
	'You can never remember Shelby\'s boyfriend\'s name and it\'s now a thing.',
	'Your weird make me comfortable in my weird.',
	'You let me keep my torn up old clothing until it can\'t be washed anymore.',
	'Every once in a while, without knowing it, you do a little shimmy and it makes me smile.',
	'You\'re a Yankees fan that misses "the good ole\' days".',
	'You slip into Pigeon the same way I slip into Pennsylvania Dutch and that makes us both weird.',
	'You invented face cakes.',
	'Your butt.',
	'What few things you cook actually taste really great.',
	'You didn\'t bail on me even when you were scared to be in a relationship.',
	'I find it impossible to have a bad day when you\'re the first and last thing I see.',
	'You\'re so stubborn that you\'ll walk around New York in the dead of winter with your jacket unbuttoned.',
	'You take interest in the things I\'m interested in.',
	'Sometimes you feel the need to be big spoon.',
	'Sexy burp.',
	'That time we saw the sumo wrestlers in Japantown.',
	'That time we said goodbye to New York and you gave me the shoulder I needed.',
	'All of the times we talked about our future together and I got that warm fuzzy feeling.',
	'That time we went to a lake and realized all little kids want to do is run around naked and poop in the woods.',
	'That time I went to watch you play soccer and you scored in your own goal.',
	'That time you served jury duty and we both realized you found your dream job.',
	'The moment you told me that it\'s OK for us to date.',
	'The moment we finally found our first apartment in San Francisco.',
	'That time you took me to Sleep No More even though you had seen it three times already.',
	'That time I tried to kiss you at a concert and instead poked you in the eye with my nose.',
	'That time we went to a children\'s museum and we sat on the floor to watch the scientist\'s crazy experiments.',
	'That time we made donuts but really I slept on your couch while you made donuts.',
	'"To be fully seen by somebody, then, and be loved anyhow - this is a human offering that can border on miraculous." - Elizabeth Gilbert',
	'"I remember who I am when I\'m with you." - Nicole Christie',
	'"O, thou art fairer than the evening air clad in the beauty of a thousand star." - Christopher Marlowe',
	'"How do I love thee? Let me count the ways. I love thee to the depth and breadth and height my soul can reach." - Elizabeth Barrett Browning',
	'"Close your eyes and I\'ll kiss you, tomorrow I\'ll miss you." - The Beatles',
	'"We love the things we love for what they are." - Robert Frost',
	'"It\'s like I never had to see it in your eyes or feel it. I could tell when you smile. It\'s like I didn\'t need to say anything or do much. I could tell when you smile." - The Flaming Lips',
	'"Morning without you is a dwindled dawn." - Emily Dickenson',
	'"When you look at me, when you thinkn of me, I am in paradise." - William Makepeace Thackeray',
	'"Love doesn\'t make the world go round. Love is what makes the ride worthwhile." - Franklin P. Jones',
	'"The touch of your hand says you\'ll catch me if ever I fall. You say it best when you say nothing at all." - Ronan Keating',
	'"So it\'s not gonna be easy. It\'s going to be really hard; we\'re gonna have to work at this everyday, but I want to do that because I want you. I want all of you, forever, everyday. You and me...every day." - Nicholas Sparks',
	'"I am in you and you in me, mutual in divine love." - William Blake',
	'"I love you - those three words have my life in them." - Alexandria',
	'"The most powerful symptom of love is a tenderness which becomes at times almost insupportable." - Victor Hugo',
	'"If you remember me, then I don\'t care if everyone else forgets." - Haruki Murakami',
	'"Two people in love, alone, isolated from the world, that\'s beautiful." - Milan Kundera',
	'"I love you, in my mind where my thoughts reside, in my heart where my emotions live, and in my soul where my dreams are born. I love you." - Dee Henderson',
	'"Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves." - Albert Einstein',
	'"The sound of a kiss is not so loud as that of a cannon, but its echo lasts a great deal longer." - Oliver Wendell Holmes, Sr.',
	'"Love doesn\'t just sit there, like a stone, it has to be made, like bread; remade all the time, made new." - Ursula K. Le Guin',
	'"The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space." - Marilyn Monroe',
	'"Love is our true destiny. We do not find the meaning of life by ourselves alone - we find it with another." - Thomas Merton',
	'You have a grandma chain on your eyeglasses.',
	'You communicate your emotions more than ever before.',
	'Tic tic tic tic tic (while moving my hands to bring in the chicken.)',
	'You LOVE my dad jokes.',
	'When I\'m with you I\'m the best version of me.',
	'The only children you like are the ones that look like they get beat up.',
	'You laugh evertime I can\'t hear you and mumble "huh".',
	'You\'ve made temporary tattoos a form of media for brands.',
	'You\'re tickelish and that always gives me an advantage.',
	'We talk like cavemen.',
	'You\'re passionate about weird music most people don\'t understand, just like me.',
	'You made me wait for you so you wouldn\'t go against your beliefs about relationship.',
	'You\'re into graphic novels and I think that\'s cool.',
	'Your best friends are important to you no matter how different you all have become.',
	'You let me pick the food off your plate. (Update: I now have to ask. That\'s okay.)',
	'You taught me that you shouldn\'t dry clean Uniqlo shirts.',
	'You have a heart for others and know how to use it.',
	'In the process of doing this, I looked back through some of our chats and it made me warm and fuzzy inside.',
	'You\'re amazed by your underarm trimmer.',
	'You wear mice on your feet, which is actually pretty funny.',
	'Originally there were some pretty blatent grammatical errors in these but you didn\'t say a thing.',
	'You know Lesean is Shady.',
	'David Akers is the only athelete you care about.',
	'You\'re still in denial about being a hipster.',
	'You\'re just as comfortable on a trail as you are on a sidewalk.',
	'Your idea of wrapping paper is a brown grocery bag.',
	'That time you kissed me so you could smudge orange paint on my face and take a picture.',
	'That time we saw Phish and you became mesmorized with a flashing hula hoop.',
	'The moment I found you in the bedroom at my parents house writhing in pain on the floor. I\'ll never forget how much it hurt to see you in such agony.',
	'That time you threatened to break up with me if I ever write a song about you.',
	'That time we pinky promised to hike in Peru...before we were dating.',
	'That time we rode the ferris wheel and it was too much excitement.',
	'That time we saw Wizard of Oz in the Castro and made our friends uncomfortable.',
	'That time in the big room. On the table. (And running into Jason on the sidewalk immediately after.)',
	'That time we decided to jumped out of a plane from 18,000 feet.', 
	'That time you took me on a sandwich bike tour in New York.',
	'That time we went to the Santa Cruz boardwalk, took the air tram and got excited to see the cavemen.',
	'That time we were on the hunt for a sweet onesie for Waylon.',
	'That time you turned me into a science experiment and kept flicking it.',
	'"Love, like everything else in life, should be a discovery, an adventure, and like most adventures, you don\'t know you\'re having one until you\'re right in the middle of it." - E.A. Bucchianeri',
	'"If I know what love is, it is because of you." - Herman Hesse',
	'"What is hell? I maintain that it is the suffering of being unable to love." - Fyodor Dostoyevsky',
	'"A kiss is a lovely trick designed by nature to stop speech when words become superfluous." - Ingrid Bergman',
	'"What\'s meant to be will always find a way." - Trisha Yearwood',
	'"What is a kiss? Why this, as some approve: The sure, sweet cement, glue, and lime of love." - Robert Herrick',
	'"Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it." - Rumi',
	'"Love is not affectionate feeling, but a steady wish for the loved person\'s ultimate good as far as it can be obtained" - C.S. Lewis',
	'"Other men said they have seen angels, but I have seen thee and thou art enough." - G. Moore',
	'"I have learned not to worry about love, but to honor its coming with all my heart." - Alice Walker',
	'"Happiness is only real when shared." - Jon Krakauer',
	'To you, lamps are high stakes.',
	'"Soul meets soul on lovers lips." - Percy Bysshe Shelley',
	'"The best thing to hold onto in life is each other." - Audrey Hepburn',
	'"Love is friendship set on fire." - Jeremy Taylor',
	'"Look after my heart - I\'ve left it with you." - Stephanie Meyer',
	'"I had a dream about you. No words were exchanged, but we spoke with our eyes. My eyes said, "I love you," while your eyes told me, "I\'m asleep." You always were more romantic than me." - Jarod Kintz',
	'That time we met each other in a dream.',
	'"Never close your lips to those whom you have already opened your heart." - Charles Dickens',
	'That time we went to LACMA and picked out our favorite DvF dresses.',
	'That time you, your dad and I made a run for it in the pouring rain outside of the temple.',
	'That time we considered the possibility of buying a boat to ferry people to and from the parking lot at Off the Grid.',
	'That time you made me into your latin lover.',
	'That time we biked to the presidio. Then to Sausalito. Then to Tiburon. Then up Russian Hill in the dark.',
	'That time your dad drove us all the way around the island because he likes US so much.',
	'That time I was your drunk, stoned man friend.',
	'That time you threw a charity event and I played bartender so I could score brownie points with you.',
	'That time you went to your first Phish show and you made friends with the hippies right around us.',
	'That time I took you to an "authentic" diner for horrible pie.',
	'That time we went for a drive on the hill by your house and saw the meth man walking in the middle of the street in the dark.',
	'That time we shoot each other, lovingly, with hard balls of paint.',
	'That time we went to Govenors Ball and I saved you with a blanket and a dry hillside.',
	'The moment we thought we were coming clean to everyone at Naked, but everyone except for Nyanza knew the whole time.',
	'That time you posed for me with a baby goat in your hands.',
	'That time I came home from a holiday party and you kept me alive.',
	'All the times I snuck your ring off your finger without you knowing. Smooth criminal.',
	'That time we played lasertag at the bar in Pennsylvania. That kid wrecked us.',
	'The moment I realized I loved you...and said "I think I love you." and you said "You think?"',
	'That time Luca visited us and wouldn\'t go back to his owner.',
	'That time you brought me orange juice to apologize.',
	'That time we helped make a playground better at an elementary school. And the cop drove us out of the neighborhood because we had no idea where we were or how dangerous it was.',
	'Your family are super cool and welcomed me with open arms.',
	'You give me shit every time I say New York City, even though there\'s an entire state called New York.',
	'You stuck with it even though you thought our first date was weird.',
	'You try to make that wrinkle between my eyebrows go away.',
	'You were into Secret Science Club and that\'s pretty nerdy.',
	'You helped me pick out glasses that make me look much smarter than I really am.',
	'You\'re trashy and like Long Island Medium. (Update: Wow. That was just the start...)',
	'You call me "Michael" in a certain way when I\'ve done something stupid.',
	'I know in your heart you have a soft spot for dogs.',
	'You don\'t consider "put your hand down my pants" an offensive statement.',
	'Your mom is really good at decorating our apartments.',
	'You don\'t like the people I don\'t like at work despite never meeting them.',
	'You passed the Leo test (staring awkwardly at each other while sitting next to each other on the couch.)',
	'Your little spoon fits in my big spoon just right.',
	'Every once in a while you try to fix my hair and it\'s quite endearing.',
	'You had a blue streak in your hair and that\'s street cred for the both of us.',
	'All you want in this life is a cute lamp.',
	'We both love to see kid movies in the theater.',
	'You have a bad pouty face but there\'s still no way I can say no.',
	'You let me keep my bed when we moved in together.',
	'You make me try things like SoulCycle.',
	'You cared enough about a piece of art to place it on your skin.',
	'You\'re the best time keeper ever when I cook.',
	'You\'ve upped my belt game.',
	'You have a nerdy calculator on your wrist.',
	'You want to be held tighter and I never want to let go.',
	'You find it entertaining to name our plants.',
	'Your favorite thing as fancy parties are the coconuts.',
	'You encourage European galivanting.',
	'That time you got me sick on my 30th birthday',
	'That time I inadvertently showed you the hole in my boxers.',
	'You tell me to say hello to Kitty',
	'That time we shot slow-mo hula dancers',
	'You helped my mom setup at my brother\'s wedding...and then dealt with freezing temperatures, rain, and my sometimes-stupid family.',
	'That time you had to sit down at the concert because Macklemore was just TOO much.',
	'That time we took surf lessons and you showed me up so bad the couple on the beach started making fun of me.',
	'You\'ve seen every holiday movie ever made.',
	'That time we became hobbits.',
	'That time we missed our flight because we were too busy talking to each other.',
	'That time that dick ate the last of my mom\'s cookies.',
	'You snack hard.',
	'You\'ve accomplished more in your life than anyone I know.',
	'That time I insulted your boss leaving the holiday party in Berkeley. (I\'m still sorry about that.)',

]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
